version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.14.2
    container_name: elasticsearch
    ports:
      - ${ES_PORT:-9200}:9200
      - "9300:9300"
    logging:
      options:
        max-size: '10m'
        max-file: '10'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=es-cluster
      - discovery.type=single-node # 单一节点模式启动
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g" # 1024m测试
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-zx.123}  # 设置密码
      - xpack.security.enabled=true

    volumes:
      - /etc/localtime:/etc/localtime:ro  # read-only
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    restart: always
    networks:
      - elk_network

  kibana:
    image: kibana:8.14.2
    container_name: kibana
    ports:
      - ${KIBANA_PORT:-5601}:5601
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - I18N_LOCALE=zh-CN
      - ELASTIC_USERNAME=${KIBANA_USER:-kibana_system}
      - ELASTIC_PASSWORD=${KIBANA_PASSWORD:-zx.123}
    volumes:
      - /etc/localtime:/etc/localtime:ro  # read-only
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana/data:/usr/share/kibana/data
    restart: unless-stopped
    depends_on:
      - elasticsearch
    networks:
      - elk_network

networks:
  elk_network:
    ipam:
      driver: default
      config:
        - subnet: 172.102.0.0/24
